name: dart_tdd
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  http: ^0.13.3
  
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  mockito: ^5.0.13
  build_runner: ^2.0.6
